version: '3'

services:
  db:
    container_name: find-a-friend-db
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: findafrienddb

  cache:
      container_name: find-a-friend-cache
      image: redis
      ports:
        - 6379:6379
      environment:
        REDIS_PASSWORD: docker
        REDIS_DB: 1
